# Install Explorer context menus for md-to-docx (current user, HKCU — no admin).
# Usage: powershell -ExecutionPolicy Bypass -File desktop/windows/install.ps1
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SrcRunner = Join-Path $ScriptDir "lib\runner.ps1"

$InstallDir = Join-Path $env:LOCALAPPDATA "md-to-docx"
$ConfFile = Join-Path $InstallDir "context-menu.conf"
$RunnerDst = Join-Path $InstallDir "runner.ps1"

function Resolve-Cli {
    if ($env:MD_TO_DOCX_CLI) {
        $p = $env:MD_TO_DOCX_CLI
        if (Test-Path -LiteralPath $p) {
            return (Resolve-Path -LiteralPath $p).Path
        }
        $cmd = Get-Command $p -ErrorAction SilentlyContinue
        if ($cmd) { return $cmd.Source }
        throw "MD_TO_DOCX_CLI is set but not found: $p"
    }
    $cmd = Get-Command "md-to-docx" -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    throw @"
md-to-docx not found on PATH.
  Install first: pip install -e .   (from the repo root)
  Or set: `$env:MD_TO_DOCX_CLI = 'C:\path\to\md-to-docx.exe'
"@
}

function Register-ShellVerb {
    param(
        [string]$Extension,
        [string]$VerbKey,
        [string]$Label,
        [string]$Action
    )
    $base = "HKCU:\Software\Classes\SystemFileAssociations\$Extension\shell\$VerbKey"
    $cmdKey = Join-Path $base "command"
    New-Item -Path $base -Force | Out-Null
    New-Item -Path $cmdKey -Force | Out-Null
    Set-ItemProperty -Path $base -Name "(default)" -Value $Label
    Set-ItemProperty -Path $base -Name "MUIVerb" -Value $Label

    # Quote paths; "%1" is the selected file from Explorer.
    $ps = Join-Path $env:SystemRoot "System32\WindowsPowerShell\v1.0\powershell.exe"
    $command = "`"$ps`" -NoProfile -ExecutionPolicy Bypass -File `"$RunnerDst`" $Action `"%1`""
    Set-ItemProperty -Path $cmdKey -Name "(default)" -Value $command
}

if (-not (Test-Path -LiteralPath $SrcRunner)) {
    throw "Missing runner: $SrcRunner"
}

$cli = Resolve-Cli
New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
Copy-Item -LiteralPath $SrcRunner -Destination $RunnerDst -Force

@"
# Generated by desktop/windows/install.ps1 — re-run install after upgrading CLI.
# PRESET empty = same as bare CLI (black headings). Set e.g. PRESET="technical" for blue.
CLI="$cli"
PRESET=""
EXTRA_ARGS=""
"@ | Set-Content -LiteralPath $ConfFile -Encoding UTF8

Register-ShellVerb -Extension ".md" -VerbKey "md-to-docx-convert" `
    -Label "Convert to Word (md-to-docx)" -Action "convert"
Register-ShellVerb -Extension ".markdown" -VerbKey "md-to-docx-convert" `
    -Label "Convert to Word (md-to-docx)" -Action "convert"
Register-ShellVerb -Extension ".docx" -VerbKey "md-to-docx-reverse" `
    -Label "Reverse to Markdown (md-to-docx)" -Action "reverse"

Write-Host ""
Write-Host "Done. CLI: $cli"
Write-Host "Config: $ConfFile"
Write-Host ""
Write-Host "In Explorer: right-click a .md or .docx file"
Write-Host "  • Convert to Word (md-to-docx)"
Write-Host "  • Reverse to Markdown (md-to-docx)"
Write-Host ""
Write-Host "Uninstall: powershell -ExecutionPolicy Bypass -File desktop/windows/uninstall.ps1"
